name: Make

on:
   pull_request:
      branches:
         - master
   push:
      branches:
         - master

jobs:
   gfortran:
      runs-on: ubuntu-latest
      steps:
         - name: Set up git user
           run: |
              git config --global user.name "koopmans-kcp-tester"
              git config --global user.email ${{ secrets.TESTER_EMAIL }}
         - name: Checkout
           uses: actions/checkout@v3
         - name: Install dependencies
           run: |
              sudo apt-get update
              sudo apt-get install gfortran libopenmpi-dev libblas-dev liblapack-dev libfftw3-dev
         - name: Configure
           run: |
              ./configure MPIF90=mpif90
         - name: Build
           run: |
              make all
         - name: Test
           run: |
              make check
         - name: Upload
           if: success() || failure()
           uses: actions/upload-artifact@v4
           with:
             name: test-data
             path: |
               tests/*/test.out.*

